// Surfaces / managed region logic (doctor, generate, preview, adopt, render_readme, etc.)

mod doctor;
mod readme;

use std::path::Path;

use anyhow::bail;
use dotrepo_schema::Manifest;

use crate::load_manifest_document;
use crate::render::{render_contributing_body, render_security_body};
use crate::util::{display_path, source_digest};
use crate::validation::validate_manifest;
use crate::{
    DoctorFinding, DoctorSurface, ManagedFileState, ManagedSurfaceAdoptionPlan, Result,
    SurfacePreviewReport,
};

pub use readme::{render_readme, render_readme_body};

pub(crate) use doctor::{
    adopt_unmanaged_surface, all_doctor_surfaces, build_managed_surface_doctor_finding,
    build_unsupported_surface_doctor_finding, default_state_message,
    ensure_native_managed_surface_record, ensure_surface_adoption_is_enabled, load_doctor_manifest,
    managed_surface_for_adoption, preview_surface,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ManagedSurface {
    Readme,
    Security,
    Contributing,
}

#[derive(Debug, Clone)]
pub(crate) struct ManagedOutput {
    pub(crate) path: std::path::PathBuf,
    pub(crate) contents: String,
}

#[derive(Debug, Clone)]
pub(crate) struct ManagedSurfaceStatus {
    pub(crate) path: std::path::PathBuf,
    pub(crate) state: ManagedFileState,
    pub(crate) current: Option<String>,
    pub(crate) message: Option<String>,
}

#[derive(Debug, Clone)]
pub(crate) struct ManagedRegion {
    pub(crate) id: String,
    pub(crate) content_start: usize,
    pub(crate) content_end: usize,
}

pub(crate) fn is_dotrepo_generated(contents: &str) -> bool {
    contents.lines().next().map(is_banner_line).unwrap_or(false)
}

pub(crate) fn is_banner_line(line: &str) -> bool {
    let trimmed = line.trim_start();
    trimmed.starts_with("<!-- generated by dotrepo")
        || trimmed.starts_with("# generated by dotrepo")
}

pub(crate) fn parse_managed_marker(line: &str, kind: &str) -> Option<String> {
    let body = line.strip_prefix("<!--")?.strip_suffix("-->")?.trim();
    let body = body.strip_prefix("dotrepo:")?;
    let body = body.trim_start();
    let body = body.strip_prefix(kind)?.trim_start();
    let body = body.strip_prefix("id")?.trim_start();
    let body = body.strip_prefix('=')?.trim();

    if body.is_empty() || body.split_whitespace().count() != 1 {
        None
    } else {
        Some(body.to_string())
    }
}

pub(crate) fn render_managed_markdown(banner: String, body: &str) -> String {
    let mut out = String::new();
    out.push_str(&banner);
    out.push('\n');
    out.push_str(body);
    out
}

pub(crate) fn render_managed_output(
    root: &Path,
    surface: ManagedSurface,
    manifest: &Manifest,
    source_bytes: &[u8],
) -> Result<Option<ManagedOutput>> {
    let digest = source_digest(source_bytes);
    let status = inspect_managed_surface(root, surface)?;
    let full_contents = match surface {
        ManagedSurface::Readme => render_readme(root, manifest, source_bytes)?,
        ManagedSurface::Security => render_managed_markdown(
            crate::render::generated_banner(crate::render::CommentStyle::Html, manifest, &digest),
            &crate::render::render_security_body(manifest),
        ),
        ManagedSurface::Contributing => crate::render::render_contributing(manifest, &digest),
    };

    let body = match surface {
        ManagedSurface::Readme => render_readme_body(root, manifest)?,
        ManagedSurface::Security => crate::render::render_security_body(manifest),
        ManagedSurface::Contributing => crate::render::render_contributing_body(manifest),
    };

    let output_path = status.path;
    let contents = match status.state {
        ManagedFileState::Missing | ManagedFileState::FullyGenerated => full_contents,
        ManagedFileState::PartiallyManaged => {
            let current = status.current.as_deref().ok_or_else(|| {
                anyhow::anyhow!(
                    "partially managed file {} is missing current contents",
                    output_path.display()
                )
            })?;
            merge_managed_region(&output_path, surface, current, &body)?
        }
        ManagedFileState::Unmanaged => return Ok(None),
        ManagedFileState::MalformedManaged | ManagedFileState::Unsupported => {
            bail!(
                "{}",
                status
                    .message
                    .unwrap_or_else(|| default_state_message(status.state))
            );
        }
    };

    Ok(Some(ManagedOutput {
        path: output_path,
        contents,
    }))
}

pub(crate) fn inspect_managed_surface(
    root: &Path,
    surface: ManagedSurface,
) -> Result<ManagedSurfaceStatus> {
    let candidate_paths = managed_surface_paths(surface)
        .iter()
        .map(|relative| root.join(relative))
        .filter(|path| path.exists())
        .collect::<Vec<_>>();

    if candidate_paths.len() > 1 {
        let paths = candidate_paths
            .iter()
            .map(|path| display_path(root, path))
            .collect::<Vec<_>>()
            .join(", ");
        return Ok(ManagedSurfaceStatus {
            path: candidate_paths[0].clone(),
            state: ManagedFileState::Unsupported,
            current: None,
            message: Some(format!(
                "multiple candidate files exist for this surface ({paths}); keep one authoritative path before enabling sync"
            )),
        });
    }

    let Some(path) = candidate_paths.first() else {
        return Ok(ManagedSurfaceStatus {
            path: root.join(managed_surface_paths(surface)[0]),
            state: ManagedFileState::Missing,
            current: None,
            message: Some("managed surface is missing".into()),
        });
    };

    let current = std::fs::read_to_string(path)
        .map_err(|err| anyhow::anyhow!("failed to read {}: {}", path.display(), err))?;
    if contains_managed_region_markers(&current) {
        return classify_marker_managed_surface(root, path, surface, current);
    }
    if is_dotrepo_generated(&current) {
        return Ok(ManagedSurfaceStatus {
            path: path.clone(),
            state: ManagedFileState::FullyGenerated,
            current: Some(current),
            message: Some("fully generated by dotrepo".into()),
        });
    }
    Ok(ManagedSurfaceStatus {
        path: path.clone(),
        state: ManagedFileState::Unmanaged,
        current: Some(current),
        message: Some(
            "file exists outside dotrepo management; unmanaged prose is preserved and does not fail generate --check by itself"
                .into(),
        ),
    })
}

fn classify_marker_managed_surface(
    root: &Path,
    path: &Path,
    surface: ManagedSurface,
    current: String,
) -> Result<ManagedSurfaceStatus> {
    match parse_managed_regions(path, &current) {
        Ok(regions) => {
            let required = managed_region_id(surface);
            if regions.len() != 1 || regions[0].id != required {
                let found = regions
                    .iter()
                    .map(|region| region.id.as_str())
                    .collect::<Vec<_>>()
                    .join(", ");
                return Ok(ManagedSurfaceStatus {
                    path: path.to_path_buf(),
                    state: ManagedFileState::Unsupported,
                    current: Some(current),
                    message: Some(format!(
                        "{} uses unsupported managed-region ids for this surface; expected only `{}`, found [{}]",
                        display_path(root, path),
                        required,
                        found
                    )),
                });
            }
            Ok(ManagedSurfaceStatus {
                path: path.to_path_buf(),
                state: ManagedFileState::PartiallyManaged,
                current: Some(current),
                message: Some(
                    "managed regions are valid; unmanaged content outside the markers is preserved"
                        .into(),
                ),
            })
        }
        Err(err) => Ok(ManagedSurfaceStatus {
            path: path.to_path_buf(),
            state: ManagedFileState::MalformedManaged,
            current: Some(current),
            message: Some(err.to_string()),
        }),
    }
}

pub(crate) fn managed_surface_paths(surface: ManagedSurface) -> &'static [&'static str] {
    match surface {
        ManagedSurface::Readme => &["README.md"],
        ManagedSurface::Security => &[".github/SECURITY.md", "SECURITY.md"],
        ManagedSurface::Contributing => &["CONTRIBUTING.md", ".github/CONTRIBUTING.md"],
    }
}

pub(crate) fn managed_region_id(surface: ManagedSurface) -> &'static str {
    match surface {
        ManagedSurface::Readme => "readme.body",
        ManagedSurface::Security => "security.body",
        ManagedSurface::Contributing => "contributing.body",
    }
}

pub(crate) fn contains_managed_region_markers(contents: &str) -> bool {
    contents.lines().any(|line| {
        let trimmed = line.trim();
        parse_managed_marker(trimmed, "begin").is_some()
            || parse_managed_marker(trimmed, "end").is_some()
    })
}

pub(crate) fn merge_managed_region(
    path: &Path,
    surface: ManagedSurface,
    current: &str,
    body: &str,
) -> Result<String> {
    let regions = parse_managed_regions(path, current)?;
    let region = regions
        .iter()
        .find(|region| region.id == managed_region_id(surface))
        .ok_or_else(|| {
            anyhow::anyhow!(
                "{} contains managed-region markers, but not the required `{}` region",
                path.display(),
                managed_region_id(surface)
            )
        })?;

    let mut out = String::with_capacity(current.len() + body.len());
    out.push_str(&current[..region.content_start]);
    out.push_str(&crate::render::ensure_trailing_newline(body));
    out.push_str(&current[region.content_end..]);
    Ok(out)
}

pub fn inspect_surface_states(root: &Path) -> Result<Vec<DoctorFinding>> {
    let mut findings = Vec::new();
    let loaded_manifest = load_doctor_manifest(root)?;

    for surface in [
        ManagedSurface::Readme,
        ManagedSurface::Security,
        ManagedSurface::Contributing,
    ] {
        let status = inspect_managed_surface(root, surface)?;
        if status.state == ManagedFileState::Missing {
            continue;
        }
        findings.push(build_managed_surface_doctor_finding(
            root,
            surface,
            status,
            loaded_manifest.as_ref(),
        )?);
    }

    for relative in [
        "CODEOWNERS",
        ".github/CODEOWNERS",
        "PULL_REQUEST_TEMPLATE.md",
        ".github/PULL_REQUEST_TEMPLATE.md",
        "pull_request_template.md",
        ".github/pull_request_template.md",
    ] {
        let path = root.join(relative);
        if !path.exists() {
            continue;
        }
        match std::fs::read_to_string(&path) {
            Ok(contents) => {
                if !is_dotrepo_generated(&contents) {
                    findings.push(build_unsupported_surface_doctor_finding(
                        relative,
                        ManagedFileState::Unsupported,
                        "conventional surface exists outside the managed-region contract for this file; keep it unmanaged or convert it to a fully generated dotrepo surface".into(),
                        loaded_manifest.as_ref(),
                    ));
                }
            }
            Err(err) => findings.push(build_unsupported_surface_doctor_finding(
                relative,
                ManagedFileState::Unsupported,
                format!("could not be read during doctor scan: {}", err),
                loaded_manifest.as_ref(),
            )),
        }
    }

    Ok(findings)
}

pub fn preview_surfaces(root: &Path, surfaces: &[DoctorSurface]) -> Result<SurfacePreviewReport> {
    let loaded_manifest = load_manifest_document(root)?;
    validate_manifest(root, &loaded_manifest.manifest)?;
    ensure_native_managed_surface_record(&loaded_manifest.manifest, "preview")?;

    let targets = if surfaces.is_empty() {
        all_doctor_surfaces().to_vec()
    } else {
        surfaces.to_vec()
    };

    let previews = targets
        .iter()
        .copied()
        .map(|surface| preview_surface(root, &loaded_manifest, surface))
        .collect::<Result<Vec<_>>>()?;

    Ok(SurfacePreviewReport {
        root: root.display().to_string(),
        previews,
    })
}

pub fn adopt_managed_surface(
    root: &Path,
    surface: DoctorSurface,
) -> Result<ManagedSurfaceAdoptionPlan> {
    let loaded_manifest = load_manifest_document(root)?;
    validate_manifest(root, &loaded_manifest.manifest)?;
    ensure_native_managed_surface_record(&loaded_manifest.manifest, "manage")?;

    let managed_surface = managed_surface_for_adoption(surface)?;
    ensure_surface_adoption_is_enabled(surface, &loaded_manifest.manifest)?;
    let status = inspect_managed_surface(root, managed_surface)?;
    let body = match managed_surface {
        ManagedSurface::Readme => render_readme_body(root, &loaded_manifest.manifest)?,
        ManagedSurface::Security => render_security_body(&loaded_manifest.manifest),
        ManagedSurface::Contributing => render_contributing_body(&loaded_manifest.manifest),
    };

    let contents = match status.state {
        ManagedFileState::Unmanaged => {
            let current = status.current.as_deref().ok_or_else(|| {
                anyhow::anyhow!(
                    "unmanaged file {} is missing current contents",
                    status.path.display()
                )
            })?;
            adopt_unmanaged_surface(managed_surface, current, &body)
        }
        ManagedFileState::Missing => {
            bail!(
                "{} is missing; `manage --adopt` only converts existing files into managed-region files",
                display_path(root, &status.path)
            )
        }
        ManagedFileState::PartiallyManaged => {
            bail!(
                "{} already contains valid managed-region markers for this surface",
                display_path(root, &status.path)
            )
        }
        ManagedFileState::FullyGenerated => {
            bail!(
                "{} is already fully generated by dotrepo; `manage --adopt` is only for existing unmanaged Markdown surfaces",
                display_path(root, &status.path)
            )
        }
        ManagedFileState::MalformedManaged | ManagedFileState::Unsupported => bail!(
            "{}",
            status
                .message
                .unwrap_or_else(|| default_state_message(status.state))
        ),
    };

    Ok(ManagedSurfaceAdoptionPlan {
        surface,
        path: status.path,
        contents,
    })
}

fn parse_managed_regions(path: &Path, contents: &str) -> Result<Vec<ManagedRegion>> {
    let mut regions = Vec::new();
    let mut seen = std::collections::BTreeSet::new();
    let mut active: Option<(String, usize, usize)> = None;
    let mut offset = 0;

    for line in contents.split_inclusive('\n') {
        let line_start = offset;
        let line_end = offset + line.len();
        offset = line_end;

        let trimmed = line.trim();
        if let Some(id) = parse_managed_marker(trimmed, "begin") {
            if active.is_some() {
                bail!(
                    "{} contains nested or overlapping managed regions; close the current region before opening `{}`",
                    path.display(),
                    id
                );
            }
            if !seen.insert(id.to_string()) {
                bail!(
                    "{} declares the managed region `{}` more than once",
                    path.display(),
                    id
                );
            }
            active = Some((id.to_string(), line_start, line_end));
            continue;
        }

        if let Some(id) = parse_managed_marker(trimmed, "end") {
            let (active_id, _begin_start, begin_end) = active.take().ok_or_else(|| {
                anyhow::anyhow!(
                    "{} closes managed region `{}` without a matching begin marker",
                    path.display(),
                    id
                )
            })?;
            if active_id != id {
                bail!(
                    "{} closes managed region `{}`, but the open region is `{}`",
                    path.display(),
                    id,
                    active_id
                );
            }
            regions.push(ManagedRegion {
                id: active_id,
                content_start: begin_end,
                content_end: line_start,
            });
        }
    }

    if let Some((id, _, _)) = active {
        bail!(
            "{} opens managed region `{}` without a matching end marker",
            path.display(),
            id
        );
    }

    Ok(regions)
}
