use dotrepo_schema::Manifest;

pub(crate) const GENERATOR_NAME: &str = "dotrepo";
pub(crate) const GENERATOR_VERSION: &str = env!("CARGO_PKG_VERSION");

pub(crate) enum CommentStyle {
    Html,
    Hash,
}

pub(crate) fn generated_banner(style: CommentStyle, manifest: &Manifest, digest: &str) -> String {
    let body = format!(
        "generated by {} {} | schema: {} | source: sha256:{}",
        GENERATOR_NAME, GENERATOR_VERSION, manifest.schema, digest
    );
    match style {
        CommentStyle::Html => format!("<!-- {} -->", body),
        CommentStyle::Hash => format!("# {}", body),
    }
}

pub(crate) fn render_contributing(manifest: &Manifest, digest: &str) -> String {
    let mut out = String::new();
    out.push_str(&generated_banner(CommentStyle::Html, manifest, digest));
    out.push('\n');
    out.push_str(&render_contributing_body(manifest));
    out
}

pub(crate) fn render_contributing_body(manifest: &Manifest) -> String {
    let mut out = String::new();
    out.push_str("# Contributing\n\n");
    out.push_str(&format!(
        "Thanks for contributing to {}.\n\n",
        manifest.repo.name
    ));
    out.push_str("## Before you open a change\n\n");
    out.push_str("- Review the repository documentation and policies.\n");
    if let Some(build) = &manifest.repo.build {
        out.push_str(&format!("- Run `{}` before submitting changes.\n", build));
    }
    if let Some(test) = &manifest.repo.test {
        out.push_str(&format!("- Run `{}` before submitting changes.\n", test));
    }
    out.push('\n');
    out.push_str("## Security\n\n");
    if let Some(contact) = manifest
        .owners
        .as_ref()
        .and_then(|owners| owners.security_contact.as_ref())
    {
        out.push_str(&format!(
            "Report suspected vulnerabilities to {} instead of opening a public issue.\n",
            contact
        ));
    } else {
        out.push_str(
            "Report suspected vulnerabilities privately to the maintainers instead of opening a public issue.\n",
        );
    }
    out
}

pub(crate) fn render_security_body(manifest: &Manifest) -> String {
    let contact = manifest
        .owners
        .as_ref()
        .and_then(|o| o.security_contact.clone())
        .unwrap_or_else(|| "the maintainers".into());
    format!(
        "# Security\n\nPlease report vulnerabilities to {}.\n",
        contact
    )
}

pub(crate) fn render_pull_request_template(manifest: &Manifest, digest: &str) -> String {
    let mut out = String::new();
    out.push_str(&generated_banner(CommentStyle::Html, manifest, digest));
    out.push('\n');
    out.push_str(&render_pull_request_template_body(manifest));
    out
}

pub(crate) fn render_pull_request_template_body(manifest: &Manifest) -> String {
    let mut out = String::new();
    out.push_str("## Summary\n\n");
    out.push_str("- Describe the user-visible change.\n\n");
    out.push_str("## Validation\n\n");
    if let Some(build) = &manifest.repo.build {
        out.push_str(&format!("- [ ] `{}`\n", build));
    }
    if let Some(test) = &manifest.repo.test {
        out.push_str(&format!("- [ ] `{}`\n", test));
    }
    if manifest.repo.build.is_none() && manifest.repo.test.is_none() {
        out.push_str("- [ ] Describe how you validated this change.\n");
    }
    out.push('\n');
    out.push_str("## Checklist\n\n");
    out.push_str("- [ ] Documentation updated where needed.\n");
    out.push_str("- [ ] Ownership, policy, and security impacts considered.\n");
    out
}

pub(crate) fn ensure_trailing_newline(body: &str) -> String {
    if body.ends_with('\n') {
        body.to_string()
    } else {
        format!("{body}\n")
    }
}
