use dotrepo_schema::Manifest;

pub(crate) const GENERATOR_NAME: &str = "dotrepo";
pub(crate) const GENERATOR_VERSION: &str = env!("CARGO_PKG_VERSION");

pub(crate) enum CommentStyle {
    Html,
    Hash,
}

pub(crate) fn generated_banner(style: CommentStyle, manifest: &Manifest, digest: &str) -> String {
    let body = format!(
        "generated by {} {} | schema: {} | source: sha256:{}",
        GENERATOR_NAME, GENERATOR_VERSION, manifest.schema, digest
    );
    match style {
        CommentStyle::Html => format!("<!-- {} -->", body),
        CommentStyle::Hash => format!("# {}", body),
    }
}

pub(crate) fn generated_output_matches(current: &str, expected: &str) -> bool {
    if current == expected {
        return true;
    }

    match (
        version_neutral_generated_output(current),
        version_neutral_generated_output(expected),
    ) {
        (Some(current), Some(expected)) => current == expected,
        _ => false,
    }
}

fn version_neutral_generated_output(contents: &str) -> Option<(&'static str, &str, &str)> {
    let (banner, body) = contents.split_once('\n')?;
    let (style, banner) = if let Some(banner) = banner.strip_prefix("<!-- generated by dotrepo ") {
        ("html", banner.strip_suffix(" -->")?)
    } else if let Some(banner) = banner.strip_prefix("# generated by dotrepo ") {
        ("hash", banner)
    } else {
        return None;
    };
    let (version, metadata) = banner.split_once(" | schema: ")?;
    if version.is_empty() || version.chars().any(char::is_whitespace) {
        return None;
    }
    if !metadata.contains(" | source: sha256:") {
        return None;
    }
    Some((style, metadata, body))
}

pub(crate) fn render_contributing(manifest: &Manifest, digest: &str) -> String {
    let mut out = String::new();
    out.push_str(&generated_banner(CommentStyle::Html, manifest, digest));
    out.push('\n');
    out.push_str(&render_contributing_body(manifest));
    out
}

pub(crate) fn render_contributing_body(manifest: &Manifest) -> String {
    let mut out = String::new();
    out.push_str("# Contributing\n\n");
    out.push_str(&format!(
        "Thanks for contributing to {}.\n\n",
        manifest.repo.name
    ));
    out.push_str("## Before you open a change\n\n");
    out.push_str("- Review the repository documentation and policies.\n");
    if let Some(build) = &manifest.repo.build {
        out.push_str(&format!("- Run `{}` before submitting changes.\n", build));
    }
    if let Some(test) = &manifest.repo.test {
        out.push_str(&format!("- Run `{}` before submitting changes.\n", test));
    }
    out.push('\n');
    out.push_str("## Security\n\n");
    if let Some(contact) = manifest
        .owners
        .as_ref()
        .and_then(|owners| owners.security_contact.as_ref())
    {
        out.push_str(&format!(
            "Report suspected vulnerabilities to {} instead of opening a public issue.\n",
            contact
        ));
    } else {
        out.push_str(
            "Report suspected vulnerabilities privately to the maintainers instead of opening a public issue.\n",
        );
    }
    out
}

pub(crate) fn render_security_body(manifest: &Manifest) -> String {
    let contact = manifest
        .owners
        .as_ref()
        .and_then(|o| o.security_contact.clone())
        .unwrap_or_else(|| "the maintainers".into());
    format!(
        "# Security\n\nPlease report vulnerabilities to {}.\n",
        contact
    )
}

pub(crate) fn render_pull_request_template(manifest: &Manifest, digest: &str) -> String {
    let mut out = String::new();
    out.push_str(&generated_banner(CommentStyle::Html, manifest, digest));
    out.push('\n');
    out.push_str(&render_pull_request_template_body(manifest));
    out
}

pub(crate) fn render_pull_request_template_body(manifest: &Manifest) -> String {
    let mut out = String::new();
    out.push_str("## Summary\n\n");
    out.push_str("- Describe the user-visible change.\n\n");
    out.push_str("## Validation\n\n");
    if let Some(build) = &manifest.repo.build {
        out.push_str(&format!("- [ ] `{}`\n", build));
    }
    if let Some(test) = &manifest.repo.test {
        out.push_str(&format!("- [ ] `{}`\n", test));
    }
    if manifest.repo.build.is_none() && manifest.repo.test.is_none() {
        out.push_str("- [ ] Describe how you validated this change.\n");
    }
    out.push('\n');
    out.push_str("## Checklist\n\n");
    out.push_str("- [ ] Documentation updated where needed.\n");
    out.push_str("- [ ] Ownership, policy, and security impacts considered.\n");
    out
}

pub(crate) fn ensure_trailing_newline(body: &str) -> String {
    if body.ends_with('\n') {
        body.to_string()
    } else {
        format!("{body}\n")
    }
}

#[cfg(test)]
mod tests {
    use super::generated_output_matches;

    #[test]
    fn generated_output_comparison_ignores_only_the_generator_version() {
        let expected = "<!-- generated by dotrepo 2.0.0-alpha.0 | schema: dotrepo/v0.1 | source: sha256:abc -->\nbody\n";
        let old_version = "<!-- generated by dotrepo 1.0.1 | schema: dotrepo/v0.1 | source: sha256:abc -->\nbody\n";
        assert!(generated_output_matches(old_version, expected));

        let old_hash_version =
            "# generated by dotrepo 1.0.1 | schema: dotrepo/v0.1 | source: sha256:abc\n* @owner\n";
        let expected_hash = "# generated by dotrepo 2.0.0-alpha.0 | schema: dotrepo/v0.1 | source: sha256:abc\n* @owner\n";
        assert!(generated_output_matches(old_hash_version, expected_hash));

        assert!(!generated_output_matches(
            "<!-- generated by dotrepo 1.0.1 | schema: dotrepo/v0.2 | source: sha256:abc -->\nbody\n",
            expected,
        ));
        assert!(!generated_output_matches(
            "<!-- generated by dotrepo 1.0.1 | schema: dotrepo/v0.1 | source: sha256:def -->\nbody\n",
            expected,
        ));
        assert!(!generated_output_matches(
            "<!-- generated by dotrepo 1.0.1 | schema: dotrepo/v0.1 | source: sha256:abc -->\nchanged\n",
            expected,
        ));
    }
}
