schema = "dotrepo/v0.1"

[record]
mode = "overlay"
status = "inferred"
source = "https://github.com/orientechnologies/orientdb"
generated_at = "2026-06-29T05:26:36.372096Z"

[record.trust]
confidence = "medium"
provenance = [
    "imported",
    "inferred",
]
notes = "Bootstrapped from `README.md`. Inferred `repo.build` from `.github/workflows/tests.yml`. Inferred `repo.test` from `.github/workflows/tests.yml`. This is an overlay bootstrap, not a maintainer-controlled canonical record."

[repo]
name = "OrientDB"
description = "**OrientDB** is an Open Source Multi-Model NoSQL DBMS with the support of Native Graphs, Documents, Full-Text search, Reactivity, Geo-Spatial and Object Oriented concepts."
homepage = "https://orientdb.dev"
license = "Apache-2.0"
visibility = "public"
languages = [
    "Batchfile",
    "CSS",
    "Dockerfile",
    "Gnuplot",
    "Groovy",
    "HTML",
    "Java",
    "JavaScript",
    "PLpgSQL",
    "SCSS",
    "Scala",
    "Shell",
    "TypeScript",
]
build = "mvn -B package --file pom.xml"
test = "mvn -B clean deploy -P all -DskipTests --file pom.xml"
topics = [
    "orientdb",
    "graph-database",
    "document-database",
    "dbms",
    "nosql",
    "graph-store",
    "multi-master",
    "multi-model-dbms",
    "database",
    "performance",
    "fast",
    "sql",
]

[docs]
root = "https://orientdb.dev"

[x.github]
archived = false
clone_url = "https://github.com/orientechnologies/orientdb.git"
default_branch = "develop"
fork = false
head_sha = "c5f6430725dbb9606b335dae34d94928acf69ec0"
html_url = "https://github.com/orientechnologies/orientdb"
stars = 4968
