schema = "dotrepo/v0.1"

[record]
mode = "overlay"
status = "verified"
source = "https://github.com/google/google-ctf"
generated_at = "2026-07-01T18:04:42.144908Z"

[record.trust]
confidence = "high"
provenance = [
    "imported",
    "verified",
]
notes = "Bootstrapped from `README.md`. This is an overlay bootstrap, not a maintainer-controlled canonical record. Auto-promoted to verified: all fields are honestly resolved."

[repo]
name = "Google CTF"
description = "This repository lists most of the challenges used in the Google CTF since 2017, as well as most of the infrastructure that can be used to run them."
homepage = "https://g.co/ctf"
license = "Apache-2.0"
visibility = "public"
languages = [
    "Python",
    "Rust",
    "C",
    "Go",
    "JavaScript",
    "C++",
    "Smali",
    "Jupyter Notebook",
    "Lua",
    "HTML",
    "Shell",
    "Dockerfile",
    "CSS",
    "Assembly",
    "PHP",
    "GLSL",
    "Makefile",
    "EJS",
    "Java",
    "Sage",
    "Nix",
    "TypeScript",
    "Perl",
    "Dart",
    "SystemVerilog",
    "CMake",
    "Blade",
    "Linker Script",
    "C#",
    "Vue",
    "Pug",
    "Verilog",
    "Starlark",
    "WebAssembly",
    "QuickBASIC",
    "NSIS",
    "Emacs Lisp",
    "jq",
    "FreeBASIC",
    "Batchfile",
    "VCL",
    "Vim Script",
    "AIDL",
    "GDB",
    "Red",
    "BASIC",
]
topics = [
    "security",
    "ctf",
    "ctf-challenges",
    "google",
]

[docs]
root = "https://g.co/ctf"

[x.github]
archived = false
clone_url = "https://github.com/google/google-ctf.git"
default_branch = "main"
fork = false
head_sha = "067421eb7e918c29e39f187fac5a0f0d72a6ab83"
html_url = "https://github.com/google/google-ctf"
stars = 4980
